### ISSUE TITLE
USBMonitor

### ISSUE THREAD

**Issue by SzAkos** [xulihang/dynamsoft-samples#2]
Hi,

I ran into a problem while trying the USBCamera project.
It builds correctly, but when I plug the USB camera into the phone the app crashes with this:
`User has not given 10306/com.dynamsoft.usbcameratest permission to access device /dev/bus/usb/001/002`

Did I miss a step?

**Comment by xulihang** [comment]
About the permission problem, you may have to check out this: https://www.dynamsoft.com/codepool/usb-camera-android-barcode-scanner.html#compatibility-issue
